# Reference: https://github.com/milvus-io/milvus/blob/master/deployments/docker/standalone/docker-compose.yml

services:
  minio-storage:
    hostname: minio-storage
    container_name: minio-storage-container
    image: minio/minio:RELEASE.2024-08-29T01-40-52Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./.data:/data
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 20s
      retries: 3
    networks:
      - chatbot

networks:
  chatbot:
    name: chatbot
    external: true